sources:
  redpanda:
    type: kafka
    bootstrap_servers: "${REDPANDA_BROKER}"
    group_id: vector-analytics
    topics:
      - analytics-events
      - analytics-errors
      - analytics-error-spans
      - analytics-web-vitals
      - analytics-vitals-spans
      - analytics-custom-events
      - analytics-custom-event-spans
      - analytics-outgoing-links
      - analytics-email-events
      - analytics-blocked-traffic
    auto_offset_reset: earliest
    sasl:
      enabled: true
      mechanism: SCRAM-SHA-256
      username: "${VECTOR_KAFKA_USER}"
      password: "${VECTOR_KAFKA_PASSWORD}"
    decoding:
      codec: json

  redpanda_metrics:
    type: prometheus_scrape
    endpoints:
      - "${REDPANDA_METRICS_ENDPOINT}"
    scrape_interval_secs: 15
    scrape_timeout_secs: 5

transforms:
  route_analytics:
    type: route
    inputs:
      - redpanda
    route:
      events: '.topic == "analytics-events"'
      errors: '.topic == "analytics-errors"'
      error_spans: '.topic == "analytics-error-spans"'
      web_vitals: '.topic == "analytics-web-vitals"'
      vitals_spans: '.topic == "analytics-vitals-spans"'
      custom_events: '.topic == "analytics-custom-events"'
      custom_event_spans: '.topic == "analytics-custom-event-spans"'
      outgoing_links: '.topic == "analytics-outgoing-links"'
      email_events: '.topic == "analytics-email-events"'
      blocked_traffic: '.topic == "analytics-blocked-traffic"'

  redpanda_metrics_transform:
    type: remap
    inputs:
      - redpanda_metrics
    source: |
      .tags.cluster = "${REDPANDA_CLUSTER_NAME}"
      .tags.env = "${ENVIRONMENT}"

sinks:
  clickhouse_events:
    type: clickhouse
    inputs:
      - route_analytics.events
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: events
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_errors:
    type: clickhouse
    inputs:
      - route_analytics.errors
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: errors
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_error_spans:
    type: clickhouse
    inputs:
      - route_analytics.error_spans
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: error_spans
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_web_vitals:
    type: clickhouse
    inputs:
      - route_analytics.web_vitals
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: web_vitals
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_vitals_spans:
    type: clickhouse
    inputs:
      - route_analytics.vitals_spans
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: web_vitals_spans
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_custom_events:
    type: clickhouse
    inputs:
      - route_analytics.custom_events
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: custom_events
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_custom_event_spans:
    type: clickhouse
    inputs:
      - route_analytics.custom_event_spans
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: custom_event_spans
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_outgoing_links:
    type: clickhouse
    inputs:
      - route_analytics.outgoing_links
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: outgoing_links
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_email_events:
    type: clickhouse
    inputs:
      - route_analytics.email_events
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: email_events
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 5000
      max_bytes: 5000000
      timeout_secs: 5
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  clickhouse_blocked_traffic:
    type: clickhouse
    inputs:
      - route_analytics.blocked_traffic
    endpoint: "${CLICKHOUSE_URL}"
    database: analytics
    table: blocked_traffic
    auth:
      strategy: basic
      user: "${CLICKHOUSE_USER}"
      password: "${CLICKHOUSE_PASSWORD}"
    batch:
      max_events: 50000
      max_bytes: 5000000
      timeout_secs: 60
    date_time_best_effort: true
    skip_unknown_fields: true
    encoding:
      timestamp_format: unix_ms

  dead_letters:
    type: file
    inputs:
      - route_analytics._unmatched
    path: /var/log/vector/dead_letters.log
    encoding:
      codec: json

  axiom_redpanda_metrics:
    type: axiom
    inputs:
      - redpanda_metrics_transform
    dataset: "${AXIOM_DATASET}"
    token: "${AXIOM_TOKEN}"
    compression: gzip
